# scripts/deploy/load-gcp-vars.ps1

$ErrorActionPreference = "Stop"

$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$PROJECT_ROOT = Resolve-Path "$SCRIPT_DIR\..\.."

. "$SCRIPT_DIR\gcp-config.ps1"

Write-Host "Setting GCP project: $PROJECT_ID"
gcloud config set project $PROJECT_ID | Out-Null
gcloud config set run/region $REGION | Out-Null

Write-Host "Loading Cloud SQL connection name..."
$INSTANCE_CONNECTION_NAME = gcloud sql instances describe $INSTANCE_NAME --format="value(connectionName)"

if ([string]::IsNullOrWhiteSpace($INSTANCE_CONNECTION_NAME)) {
    throw "Failed to load INSTANCE_CONNECTION_NAME. Check Cloud SQL instance name."
}

Write-Host "Cloud SQL connection name: $INSTANCE_CONNECTION_NAME"

Write-Host "Loading Redis host..."
$REDIS_HOST = gcloud redis instances describe $REDIS_INSTANCE --region=$REGION --format="value(host)"

if ([string]::IsNullOrWhiteSpace($REDIS_HOST)) {
    throw "Failed to load REDIS_HOST. Check Memorystore instance name/region."
}

Write-Host "Redis host: $REDIS_HOST"

$IMAGE_URI = "$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME`:latest"
$CLOUD_SQL_DATABASE_URL = "postgresql+psycopg2://$DB_USER`:$DB_PASSWORD@/$DB_NAME`?host=/cloudsql/$INSTANCE_CONNECTION_NAME"
$PROD_REDIS_URL = "redis://$REDIS_HOST`:6379/0"

$SERVICE_URL = gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)" 2>$null

Write-Host ""
Write-Host "Computed values:"
Write-Host "IMAGE_URI=$IMAGE_URI"
Write-Host "CLOUD_SQL_DATABASE_URL=$CLOUD_SQL_DATABASE_URL"
Write-Host "PROD_REDIS_URL=$PROD_REDIS_URL"
Write-Host "SERVICE_URL=$SERVICE_URL"
Write-Host ""

# Generate Cloud Run env file.
$cloudRunEnv = @"
DATABASE_URL: "$CLOUD_SQL_DATABASE_URL"
JWT_SECRET_KEY: "$JWT_SECRET_KEY"
JWT_ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: "$ACCESS_TOKEN_EXPIRE_MINUTES"
REFRESH_TOKEN_EXPIRE_DAYS: "$REFRESH_TOKEN_EXPIRE_DAYS"
REDIS_URL: "$PROD_REDIS_URL"
GEOCODING_CACHE_TTL_SECONDS: "$GEOCODING_CACHE_TTL_SECONDS"
SEARCH_CACHE_TTL_SECONDS: "$SEARCH_CACHE_TTL_SECONDS"
RATE_LIMIT_PER_MINUTE: "$RATE_LIMIT_PER_MINUTE"
RATE_LIMIT_PER_HOUR: "$RATE_LIMIT_PER_HOUR"
US_CENSUS_GEOCODER_URL: "$US_CENSUS_GEOCODER_URL"
US_CENSUS_BENCHMARK: "$US_CENSUS_BENCHMARK"
ZIPPOPOTAMUS_URL: "$ZIPPOPOTAMUS_URL"
"@

$cloudRunEnvPath = "$PROJECT_ROOT\cloudrun-env.generated.yaml"
$cloudRunEnv | Out-File -FilePath $cloudRunEnvPath -Encoding utf8

Write-Host "Generated: $cloudRunEnvPath"

# Generate reusable variable file.
$varsFile = @"
# Auto-generated by scripts/deploy/load-gcp-vars.ps1

`$PROJECT_ID = "$PROJECT_ID"
`$REGION = "$REGION"
`$SERVICE_NAME = "$SERVICE_NAME"
`$REPO_NAME = "$REPO_NAME"
`$IMAGE_NAME = "$IMAGE_NAME"
`$INSTANCE_NAME = "$INSTANCE_NAME"
`$INSTANCE_CONNECTION_NAME = "$INSTANCE_CONNECTION_NAME"
`$DB_NAME = "$DB_NAME"
`$DB_USER = "$DB_USER"
`$DB_PASSWORD = "$DB_PASSWORD"
`$REDIS_INSTANCE = "$REDIS_INSTANCE"
`$REDIS_HOST = "$REDIS_HOST"
`$VPC_CONNECTOR = "$VPC_CONNECTOR"
`$IMAGE_URI = "$IMAGE_URI"
`$CLOUD_SQL_DATABASE_URL = "$CLOUD_SQL_DATABASE_URL"
`$PROD_REDIS_URL = "$PROD_REDIS_URL"
`$SERVICE_URL = "$SERVICE_URL"
"@

$varsFilePath = "$PROJECT_ROOT\gcp-vars.generated.ps1"
$varsFile | Out-File -FilePath $varsFilePath -Encoding utf8

Write-Host "Generated: $varsFilePath"
Write-Host ""
Write-Host "Done."